document.writeln('<header>');
document.writeln('	<nav id="nav">');
document.writeln('		<ul>');
document.writeln('			<li><a href="/index.html" >网站首页</a></li>');
document.writeln('			<li><a href="/1/index.html" title="Java">Java</a></li>');
document.writeln('			<li><a href="/2/index.html" title="Android">Android</a></li>');
document.writeln('			<li><a href="/3/index.html" title="HTML5 / CSS3">HTML5 / CSS3</a></li>');
document.writeln('			<li><a href="/4/index.html" title="Linux">Linux</a></li>');
document.writeln('			<li><a href="/5/index.html" title="技术探讨">技术探讨</a></li>');
document.writeln('			<li><a href="/6/index.html" title="慢生活">慢生活</a></li>');
document.writeln('			<li><a href="/7/index.html" title="碎言碎语">碎言碎语</a></li>');
document.writeln('			<li><a href="/guestbook.html" title="留言板">留言版</a></li>');
document.writeln('		</ul>');
document.writeln('		<script src="js/silder.js"></script><!--获取当前页导航 高亮显示标题-->');
document.writeln('	</nav>');
document.writeln('</header>');